"""Updated connections between User, UserAgreement and PrivacyPolicy 2

Revision ID: 084ce69fb855
Revises: d6411cea3f6b
Create Date: 2025-05-31 01:54:37.446245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084ce69fb855'
down_revision: Union[str, None] = 'd6411cea3f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
