"""Added language_code to UserAgreement and PrivacyPolicy

Revision ID: 848db3a0ddfb
Revises: 084ce69fb855
Create Date: 2025-05-31 11:48:42.001437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848db3a0ddfb'
down_revision: Union[str, None] = '084ce69fb855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('privacy_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_code', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint('unique_privacy_policy_version_language_code', ['version', 'language_code'])

    with op.batch_alter_table('user_agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_code', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint('unique_agreement_version_language_code', ['version', 'language_code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_agreements', schema=None) as batch_op:
        batch_op.drop_constraint('unique_agreement_version_language_code', type_='unique')
        batch_op.drop_column('language_code')

    with op.batch_alter_table('privacy_policies', schema=None) as batch_op:
        batch_op.drop_constraint('unique_privacy_policy_version_language_code', type_='unique')
        batch_op.drop_column('language_code')

    # ### end Alembic commands ###
