"""User model restructure and add of Payment and PromoCode

Revision ID: d97ee12af660
Revises: 0ed2235dd46c
Create Date: 2025-05-29 10:52:53.206377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97ee12af660'
down_revision: Union[str, None] = '0ed2235dd46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('uses_limit', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subscription_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('trial_starts_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_starts_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_autorenew', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('subscription_cancelled_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('timezones')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezones', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('subscription_cancelled_at')
        batch_op.drop_column('subscription_autorenew')
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('subscription_starts_at')
        batch_op.drop_column('subscription_type')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('trial_starts_at')
        batch_op.drop_column('timezone')

    op.drop_table('payments')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
