"""Updated User model. Added time_format, confirmed_admin_id, confirmed_at

Revision ID: f16eb3e06651
Revises: 4fdb6231e9ba
Create Date: 2025-05-30 13:05:06.611680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16eb3e06651'
down_revision: Union[str, None] = '4fdb6231e9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_format', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('confirmed_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('confirmed_admin_id')
        batch_op.drop_column('time_format')

    # ### end Alembic commands ###
